config/routes.rb
Rails.application.routes.draw do

  resources :rooms
  resources :structure_types
  resources :e_responses
  resources :time_tables
  get 'su/index'
  resources :jfn_support_courses
  get 'jfn/index'
  get 'jfn/admin_index'
  get 'enseignant/index'
  get 'enseignant/import'
  get 'enseignant/list'
  get 'enseignant/affectation'
  get 'enseignant/statistic'
  get 'student/index'
  get 'student/import'
  get 'demo/index'
  get 'demo/form'
  get 'demo/fuse'
  resources :trs
  resources :yrs
  resources :sequences
  resources :trimestres
  resources :annee_scolaires
  mount Notifications::Engine => '/notifications'
  #get 'share/title:string'
  devise_for :tuteurs
  resources :blogs
  resources :epreuves
  resources :messages
  resources :problemes
  #get 'people/search'

  # import data
  post 'import_gsbnal_data', to: 'salle_de_classes#import_gsbnal_data'


  resources :documents
  resources :comments
  resources :classe_matieres
  root 'welcome#index'

  scope :shares do
    get 'share', to: 'welcome#shares'
    get 'file_share_detail', to: 'welcome#file'
    match 'check_me_mppp', to: 'welcome#confirm_user_email_ip', via: [:post, :get]
    get 'max_share_reached', to: 'welcome#max_share_reached'
  end

  # for help
  get 'yelp', to: 'home_student#help'

  scope :nalos do
    get 'services', to: 'welcome#services'
    get 'actualites', to: 'welcome#actualites'
  end


  resources :local_news
  resources :teacher_classes
  resources :matieres
  scope :matiere  do
    get 'filieres_mat', to: 'matieres#filieres'
  end
  get 'admin/index'
  resources :courses
  resources :filieres
  get 'home_student/index'
  #devise_for :students
  devise_for :students, controllers: {
      sessions: 'student/sessions',
      registrations: 'student/registrations'
  }
  resources :cycle_ecoles
  # devise_for :users
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }
  resources :roles
  resources :salle_de_classes
  resources :enseignements
  resources :structures
  get 'home/index'
  #root 'home#index'

  # gestion et liste des partenaires
  scope :partners do
    get 'partners', to: "partenaire#index"
    get 'app', to: 'partenaire#app'
  end

  post 'importation', to: 'home#importation'

  scope :teacher do
    get 'apprenant', to: 'home#apprenants'
    get 'salle_classe', to: 'home#classes'
    get 'inside_classe', to: 'home#go_to_classe'
    match 'send_sms_notification_to_classe', to: 'home#send_sms_notification_to_classe', via: [:post, :get] # send notification to classeroom
    get 'apprenant_details', to: 'home#apprenant_details'
    get 'student_par_classe', to: 'home#student_par_classe'
    get 'student_par_filiere', to: 'home#student_par_filiere'
    get 'dashboard', to: 'home#dashboard'
    get 'discuss', to: 'home#discuss'

    scope :discus do
      get 'discus_chat', to: 'home#discus_chat'
      get 'discus_video', to: 'home#discus_video'
      get 'discus_schedul', to: 'home#discus_schedul'
    end

    scope :blog do
      get 'blog_index', to: 'home#blog_index'
    end

    get 'planning', to: 'home#planning'

    # gestion des elements du dashboard
    scope :dashboard do
      get 'course_dash', to: 'home#course_dash'
      get 'epreuves_dash', to: 'home#epreuve_dash'
      get 'documents_dash', to: 'home#document_dash'
    end

    #gestion des epreuves
    scope :epreuves do
      get 'epreuve', to: 'home#epreuves'
    end

    scope :messagerie do
      get 'msg', to: 'home#messagerie'
      get 'read_message', to: 'home#read_message'
      match 't_message', to: 'home#t_message', via: [:post, :get]
    end

    # gestion des live course
    scope :live_course do
      get 'live_course/index'
      get 'test_webrtc', to: 'live_course#test_webrtc'
    end

    # document sections
    scope :documents do
      get 'detail_content', to: 'documents#detail_content'
      get 'join_to_course', to: 'documents#join_to_course'
      post 'create_course_from_document', to: 'documents#create_course_from_document'
      get 'preview_course', to: 'documents#preview_course'
    end
  end
  # admin scope
  scope :admin do
    get 'index', to: 'admin#index'
    get 'read_active_document', to: 'admin#read_active_document'
    get 'index_new', to: 'admin#index_new'
    get 'stats', to: 'admin#stats_index'
    root 'admin#index', as: 'admin_route'
    get 'set_role', to: 'admin#set_role'
    get 'set_role_root', to: 'admin#set_role_root'

    # openTok stream
    get 'stream', to: 'admin#stream'


    # setup plateforme
    scope :setup do
      # liste des apprenants
      get 'setup_liste_apprenants', to: 'setup#liste_apprenants'
      get 'setup_incomplete_students', to: 'setup#liste_incomplet_apprenants'
      get 'detail_apprenant', to: 'setup#detail_apprenant'
      match 'update_apprenant', to: 'setup#update_apprenant', via: [:post, :get, :put]
      get 'manage_structure', to: "structures#manage_structure"
      get 'manage_student', to: 'students#index'
      get 'list_students', to: 'student#list'

      # gestion des ensiengnats
      get 'manage_enseignant', to: 'enseignant#index'

      # academic year
      get 'academic_year', to: 'setup#academic_year'
      get 'academic_section', to: 'setup#academic_section'
      get 'academic_salle_de_class', to: 'setup#academic_salle_de_class'

      # setup index
      get 'setup_index', to: 'setup#index'
      get 'setup_enseignant_index', to: 'setup#enseignant_index'
      get 'setup_manage_enseignant_index', to: 'setup#manage_enseignant_index'
      get 'deleted_teachers_list', to: 'setup#manage_enseignant_deleted'
      match 'setup_new_teacher', to: 'setup#new_teacher', via: [:post, :patch, :delete] # ajuoter un nouvel enseignant
      get 'setup_student_index', to: 'setup#student_idenx'
      get 'setup_notification_index', to: 'setup#notification_index'
      get 'setup_course_index', to: 'setup#course_index'
      match 'manage_matiere', to: 'setup#manage_matiere', via: [:post, :get, :delete]
      get 'setup_structure_list'  , to: 'setup#structure_list'
      get 'setup_structure_index', to: 'setup#structure_index'
      get 'setup_manage_structure_index', to: 'setup#manage_structure_index' # permet de manager un structure

      # update teacher password
      match 'update_my_t_pwd', to: 'setup#update_password', via: [:get, :post]

      # restaure teacher from deleted
      get 'restaure_teacher', to: 'setup#restaure_teacher_account'

      # manage API
      get 'setup_manage_api', to: 'setup#manage_api'
      get 'document_word_server', to: 'setup#document_word_server'
      get 'document_calc_server', to: 'setup#document_calc_server'
      get 'document_powerpoint_server', to: 'setup#document_powerpoint_server'
      # end managing API

      match 'setup_add_new_structure', to: 'setup#new_structure', via: [:post, :get, :delete] # ajout d'une nouvelle strcture
      post 'setup_update_structure', to: 'setup#update_structure' # update structure
      get 'setup_droits_index', to: 'setup#droits_index'
      get 'setup_root_structure', to: 'setup#root_structure' # gestion des utilisateurs root
      get 'setup_new_root_select', to: 'setup#new_root_select' # lister les utilisateurs qui seront les prochains root
      post 'setup_enseignant_root_role', to: 'admin#enseignant_root_role'

      # gestion des aspects liés aux matiere de la plateforme
      get 'setup_matiere_index', to: 'setup#matiere_index'
      match 'setup_new_matiere', to: 'setup#new_matiere', via: [:post, :get, :delete, :patch]
      # fin de la gestion des matiere

      # affectation
      get 'affectation_details', to: 'teacher_classes#details'
      delete 'delete_affectation', to: 'teacher_classes#delete_affectation'


      # gestion de la partie liés au notifications

      # finc de la gestion des notifications
    end

    scope :courses do
      get 'course_all', to: 'admin#course_all'
      get 'course_all_detail', to: 'admin#course_all_detail'
      get 'who_read_course', to: 'admin#who_read_course'
      get 'course_detail', to: 'admin#course_detail'
      get 'course_detail_contact_teacher', to: 'admin#course_detail_contact_teacher'
      match 'course_send_teacher_note', to: 'admin#course_send_teacher_note', via: [:get, :post]

      # CRM interface
      get 'crm', to: 'admin#crm'
      get 'calendar', to: 'admin#calendar'

      # course validation
      scope :validation do
        post 'course_validation', to: 'admin#course_validation'
        get 'course_suspension', to: 'admin#course_suspension'
        post 'course_validate_or_suspend_all', to: 'admin#course_validate_or_suspend_all'
        get 'course_delete', to: 'admin#course_delete'
      end
    end

    scope :documents do
      get 'document_all', to: 'admin#document_all'
    end

    # Managing account
    scope :account do
      get 'accounts', to: 'admin#accounts'

      # Managing matieres
      scope :matieres do
        get 'index_matieres', to: 'admin#matieres'
      end

      scope :enseignants do
        get 'index_enseignants', to: 'admin#enseignants'
        get 'teachers', to: 'admin#teachers'
      end

      scope :salle_classes do
        get 'index_salle_classes', to: 'admin#salle_classes'
      end


      # import account information
      scope :import do
        get 'import_teacher', to: 'admin#import_teacher'
        post 'import_teacher_intent', to: 'admin#import_teacher_intent'
        get 'import_student', to: 'admin#import_student'
        post 'import_student_intent', to: 'admin#import_student_intent'

        # matiere import
        post 'import_matiere_intent', to: 'admin#import_matiere_intent'
        match 'import_matiere_form', to: 'admin#import_matiere_form', via: [:get, :post]

        # enseignant import
        post 'import_enseignant_intent', to: 'admin#import_enseignant_intent'

        # salle de classe
        post 'import_salle_classe_intent', to: 'admin#import_salle_classe_intent'
      end
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:discus_chat, :messagerie, :t_message]
  before_action :update_comment_readed, only: :read_message

  def index
    if current_user.role.name == 'teacher'

      @current_course = Course.where(user_id: current_user.id, deleted: false).order(created_at: :desc)
      @local_news = LocalNews.all.order(created_at: :desc)
      @time_table = TimeTable.all

    elsif current_user.role.name == 'principale'

      redirect_to admin_index_path, notice: 'Redirection forcée vers cette page!'

    elsif current_user.role.name == 'admin'

      redirect_to setup_index_path

    end
  end

  # new teacher message
  def t_message
    if request.get?
    else
      new_message = Message.new(message_white_list)
      if new_message.save
        redirect_to msg_path, notice: "Message envoyé avec succès"
      else
        redirect_to msg_path, notice: "Eche de l'envoi du message : #{new_message.errors.messages}"
      end
    end
  end

  # teacher messagerie
  def messagerie
    @comments = [] #Comment.where(user_id: current_user.id)
    @messages = Message.where(user_id: current_user.id).order(created_at: :desc)
  end

  def importation
    TeacherClasse.import(params[:file])
    redirect_to teacher_classes_path, notice: 'Toutes les affectations ont été importées'
  end

  # epreuves
  def epreuves

  end

  # read message
  def read_message
    if params[:a].present?
      @message = Message.find(params[:msg_id])
    else
      @current_comment = Comment.find_by(metakey: params[:key])
      @current_course = Course.find(@current_comment.course_id)
    end
  end

  def dashboard

  end

  def discuss
    if current_user.role.name == "root"

    else
      salle_id = current_user.salle_de_class_id
      @room = SecureRandom.hex(10)
      @etablissement = current_user.structure.name
      @classe = TeacherClasse.where(user_id: current_user.id) #.group(:salle_de_class_id)
    end
  end

  # discus text actionCable
  def discus_chat
    if user_signed_in?
      @url = request.url
      @current_classe = SalleDeClass.find_by_token(params[:token])
      @current_students = Student.where(salle_de_class_id: @current_classe.id).page(params[:page]).per(10)
    else
      render layout: false
    end
  end

  # discus video actionCable + webRTC
  def discus_video

  end

  # programmer un discus
  def discus_schedul

  end

  def apprenants
    #@apprenant = Student.where(structure_id: current_user.structure_id, salle_de_class_id: current_user.salle_de_class_id).order(:name).page(params[:page]).per(50)  #all.where(salle_de_class_id: current_user.salle_de_class_id).order(:name)
    # Recherche des salles de classe de l'enseignant
    @current_classes = TeacherClasse.where(user_id: current_user.id).page(params[:page]).per(10)
    #@current_classes = SalleDeClass.where(structure_id: current_user.structure_id, id: current_classes.salle_de_class_id)

  end

  # details sur un apprenant
  def apprenant_details
    data = params[:id]
    @apprenant_details = Student.find(data)
  end

  #dashboard sur les cours
  def course_dash

  end

  # permet d'afficher les etudiants par classe
  def student_par_classe
    @student_par_class = SalleDeClass.find(current_user.salle_de_class_id)
  end

  # permet d'afficher les etudiants par filiere
  def student_par_filiere
    @student_par_filiere = Filiere.all.where(salle_de_class_id: current_user.salle_de_class_id)
  end

  def classes
    salle_id = current_user.salle_de_class_id
    @classe = TeacherClasse.where(user_id: current_user.id) #.group(:salle_de_class_id)
  end

  # acceder à une salle de classe
  def go_to_classe
    @classe = SalleDeClass.find_by(token: params[:token])
    if @classe.nil?
      redirect_to salle_classe_path, notice: "Aucun apprenants n'a été trouvé dans cette salle de classe."
    else
      @students = Student.where(salle_de_class_id: @classe.id).page(params[:page]).per(10)
    end
  end

  # send SMS notification to all student/parent classe
  def send_sms_notification_to_classe
    if request.get?
      @current_classe = SalleDeClass.find_by(token: params[:classe], structure_id: current_user.structure_id)
      @current_student_phone = Student.where(salle_de_class_id: @current_classe.id).where("phone != '' ").count
    elsif request.post?
      # make post request
      if params[:all].present?
        # send SMS to all student

      elsif params[:selection].present?
        # send SMS to selected student

      end
    end
  end

  # send sms intent to all class
  # post
  def send_sms_notification_to_classe_intend
    @current_classe = SalleDeClass.find_by_token(params[:classe])

    # get current message
    current_message = params[:message]

    # get teacher informations
    current_teacher = current_user.complete_name

    # inspecting all student with phone number
    Student.where(salle_de_class_id: @current_classe.id).where("phone != ''").each do |student|
      SmsJob.set(wait: 2.minutes).perform_later(phone: student.phone, msg: " .#{current_teacher.upcase}", structure: current_user.structure.name.upcase)
    end
  end

  # plannig de validation
  def planning
    @planning = Course.where(user_id: current_user.id, deleted: false).order(created_at: :desc)
  end

  # managing blog
  def blog_index
    @blogs = Blog.all.page(params[:page]).per(4)
  end

  private

  def teacher_presence
    if current_user.role == "teacher"

    end
  end

  # message messaging informations
  def message_white_list
    params.permit(:user_id, :student_id, :subject, :content)
  end

  # update message or comment reading
  def update_comment_readed
    if params[:a].present?
      # nil action
    else
      Comment.find_by(metakey: params[:key]).update(read: true)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="flex items-center justify-between mb-4">
  <h2 class="text-xl font-bold text-gray-800">Emploi du temps</h2>
  <a href="#" class="text-blue-600 hover:text-blue-500 font-medium">
    <%= link_to "Tout voir", planning_path, class: "hover:bg-transparent hover:text-indigo-500" %>
  </a>
</div>

<br>

<!--
  Tailwind UI components require Tailwind CSS v1.8 and the @tailwindcss/ui plugin.
  Read the documentation to get started: https://tailwindui.com/documentation
-->
<% if @time_table.empty? %>



<% else %>

  <div class="flex flex-col">
    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-200">
            <thead>
            <tr>
              <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                date debut
              </th>
              <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                Date fin
              </th>
              <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                Filière
              </th>
              <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                salle de classe
              </th>
              <th class="px-6 py-3 bg-gray-50" colspan="2"></th>
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
            <% @time_table.each do |time_table| %>
              <tr>
                <td class="px-6 py-4 whitespace-no-wrap">
                  <div class="flex items-center">
                    <div class="flex-shrink-0 h-10 w-10">
                      <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=facearea&amp;facepad=4&amp;w=256&amp;h=256&amp;q=60" alt="">
                    </div>
                    <div class="ml-4">
                      <div class="text-sm leading-5 font-medium text-gray-900">
                        <%= time_table.periode_debut.to_date.strftime("%d %b %Y") %>
                      </div>
                      <% if Date.today > time_table.periode_fin.to_date %>
                        <div class="text-sm leading-5 text-red-500">
                          Emploi du temps périmé, invalide
                        </div>
                      <% else %>
                        <div class="text-sm leading-5 text-green-500">
                          Valide et en cours
                        </div>
                      <% end %>
                    </div>
                  </div>
                </td>
                <td class="px-6 py-4 whitespace-no-wrap">
                  <div class="text-sm leading-5 text-gray-900"><%= time_table.periode_fin.to_date.strftime("%d %b %Y") %></div>
                  <div class="text-sm leading-5 text-gray-500"><%= time_table.structure.name %></div>
                </td>
                <td class="px-6 py-4 whitespace-no-wrap">
                  <div class="text-sm leading-5 text-gray-900"><%= time_table.filiere.name %></div>
                  <div class="text-sm leading-5 text-gray-500">Optimization</div>
                </td>
                <td class="px-6 py-4 whitespace-no-wrap">
                <span class="px-2 inline-flex text-xs leading-5 font-semibold">
                  <%= time_table.salle_de_class.name %>
                </span>
                </td>
                <td class="px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium">
                  <% if Date.today > time_table.periode_fin.to_date %>

                  <% else %>
                    <%= link_to 'Show', time_table, class: "text-indigo-600 hover:text-indigo-900" %>
                  <% end %>
                </td>
                <td class="px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium">
                  <%= link_to 'Supprimer', time_table, method: :delete, data: {confirm: 'Confirmer la suppression de cet emploi du temps?'}, class: "text-indigo-600 hover:text-indigo-900" %>
                </td>
              </tr>
            <% end %>

            <!-- More rows... -->
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

<% end %>

<div>
  <div class="flex items-center justify-between mb-8 mt-10">
    <h2 class="text-xl font-bold text-gray-800"><%= t('last_post', locale: :fr) %></h2>
    <%= link_to "Voir tous mes cours", courses_path, class: "text-blue-600 hover:text-blue-500 font-medium bg-transparent hover:bg-transparent hover:text-indigo-500" %>
  </div>

  <% if @current_course.count.zero? %>
    <div class="md:flex bg-transparent rounded-lg p-6 text-center justify-center">

      <div class="md:flex bg-transparent rounded-lg p-6 text-center justify-center">

        <%= image_tag('iconfinder_box-empty-play-button-video_3993859.png', class: 'mr-4 opacity-50 mx-auto md:mx-0 md:mr-6 w-100 h-100', height: 100, width: 100) %>

        <div class="text-center md:text-left">
          <h2 class="text-lg mt-8">Pas de leçons trouvées.</h2> <br>
          <%= link_to "Publier une nouvelle leçon?", documents_path, class: "hover:bg-transparent hover:text-indigo-500" %>
        </div>
      </div>

    </div>
  <% else %>

    <%= render 'layouts/course_template', courses: @current_course %>

  <% end %>
</div>

<div class="py-8">
  <div class="flex items-center justify-between mb-8 mt-10">
    <h2 class="text-xl font-bold text-gray-800">Babillard d'informations</h2>
    <%= link_to "Voir toutes les informations", "#", class: "text-blue-600 hover:text-blue-500 font-medium bg-transparent hover:bg-transparent hover:text-indigo-500" %>
  </div>

  <% if @local_news.empty? %>
    <div class="md:flex bg-transparent rounded-lg p-6 text-center justify-center">

      <div class="md:flex bg-transparent rounded-lg p-6 text-center justify-center">

        <%= image_tag('iconfinder_video-slides-layers-player-ui_3993849.png', class: 'mr-4 opacity-50 mx-auto md:mx-0 md:mr-6 w-100 h-100', height: 100, width: 100) %>

        <div class="text-center md:text-left">
          <h2 class="text-lg mt-8">Babillard vide pour le moment.</h2> <br>
        </div>
      </div>

    </div>
  <% else %>
    <div class="">
      <div class="">
        <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
          <div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
            <table class="min-w-full leading-normal">
              <thead>
              <tr>
                <th
                  class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                  activite
                </th>
                <th
                  class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                  extrait
                </th>
                <th
                  class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                  date publication
                </th>
                <th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Statut</th>
              </tr>
              </thead>
              <tbody>
              <% @local_news.each do |news| %>
                <tr>
                  <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                    <div class="flex items-center">
                      <div class="flex-shrink-0 w-10 h-10">
                        <%= image_tag 'info.png', class: "w-full h-full" %>
                      </div>
                      <div class="ml-3">
                        <p class="text-gray-900 whitespace-no-wrap">
                          <%= news.title %>
                        </p>
                      </div>
                    </div>
                  </td>
                  <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                    <p class="text-gray-900 whitespace-no-wrap">
                      <%= excerpt(news.extrait, '', radius: 20) %>
                    </p>
                  </td>
                  <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                    <p class="text-gray-900 whitespace-no-wrap">
                      <%= news.created_at.strftime("%d %b %Y") %>
                    </p>
                  </td>
                  <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                  <span
                    class="relative inline-block px-3 py-1 font-semibold text-green-900 leading-tight">
                      <span aria-hidden
                            class="absolute inset-0 bg-green-200 opacity-50 rounded-full"></span>
                      <span class="relative"><%= news.statut %></span>
                  </span>
                  </td>
                  <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                  <span
                    class="relative inline-block px-3 py-1 font-semibold leading-tight">
                      <span aria-hidden class="absolute inset-0 bg-green-200 opacity-50 rounded-full"></span>
                      <span class="relative"><%= link_to "Consulter", local_news_path(news), class: "hover:bg-transparent hover:text-indigo-500" %></span>
                  </span>
                  </td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/home/send_sms_notification_to_classe.html.erb
<div class="bg-gray-50">
  <div class="max-w-screen-xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8 lg:flex lg:items-center lg:justify-between">
    <h2 class="text-3xl leading-9 font-extrabold tracking-tight text-gray-900 sm:text-4xl sm:leading-10">
      Notifier toute la classe de
      <br />
      <span class="text-indigo-600"><%= @current_classe.name %> (<%= @current_student_phone %>) élèves</span>
    </h2>
    <div class="mt-8 flex lg:flex-shrink-0 lg:mt-0">
      <div class="ml-3 inline-flex rounded-md shadow">
        <%= link_to "Retourner à la liste des élèves", inside_classe_path(token: params[:token]), class: "inline-flex items-center justify-center px-5 py-3 border border-transparent text-base leading-6 font-medium rounded-md text-indigo-600 bg-white hover:text-indigo-500 focus:outline-none focus:shadow-outline transition duration-150 ease-in-out" %>
      </div>
    </div>
  </div>
</div>

<div>
  <%= form_with(url: setup_add_new_structure_path) do |form| %>
    <main class="flex-1 md:p-0 lg:pt-8 lg:px-8 md:ml-2 flex flex-col">
      <section class="bg-white p-4 shadow">
        <div class="md:flex">
          <h2 class="md:w-1/3 uppercase tracking-wide text-sm sm:text-lg mb-6">Nouveau message</h2>
        </div>
        <form>
          <div class="md:flex mb-6">
            <div class="md:w-1/3">
              <legend class="uppercase tracking-wide text-sm">Contenu du message</legend>
            </div>
            <div class="md:flex-1 mt-2 mb:mt-0 md:px-3">
              <%= text_area(:message, :lorem, class: "inline-flex items-center justify-center px-5 py-3 border border-transparent text-base leading-6 font-medium rounded-md text-white bg-gray-300 hover:bg-gray-200 focus:outline-none focus:shadow-outline transition duration-150 ease-in-out p-12", cols: "80%", rows: 10) %>
            </div>
          </div>
          <div class="md:flex mb-6">
            <div class="md:flex-1 px-3 text-center md:text-right">
              <input type="hidden" name="sponsor" value="0">
              <%= form.submit "Envoyer le SMS", class: "inline-flex items-center justify-center px-5 py-3 border border-transparent text-base leading-6 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline transition duration-150 ease-in-out" %>
            </div>
          </div>
        </form>
      </section>
    </main>
  <% end %>
</div>