config/routes.rb
Rails.application.routes.draw do

  resources :rooms
  resources :structure_types
  resources :e_responses
  resources :time_tables
  get 'su/index'
  resources :jfn_support_courses
  get 'jfn/index'
  get 'jfn/admin_index'
  get 'enseignant/index'
  get 'enseignant/import'
  get 'enseignant/list'
  get 'enseignant/affectation'
  get 'enseignant/statistic'
  get 'student/index'
  get 'student/import'
  get 'demo/index'
  get 'demo/form'
  get 'demo/fuse'
  resources :trs
  resources :yrs
  resources :sequences
  resources :trimestres
  resources :annee_scolaires
  mount Notifications::Engine => '/notifications'
  #get 'share/title:string'
  devise_for :tuteurs
  resources :blogs
  resources :epreuves
  resources :messages
  resources :problemes
  #get 'people/search'

  # import data
  post 'import_gsbnal_data', to: 'salle_de_classes#import_gsbnal_data'


  resources :documents
  resources :comments
  resources :classe_matieres
  root 'welcome#index'

  scope :shares do
    get 'share', to: 'welcome#shares'
    get 'file_share_detail', to: 'welcome#file'
    match 'check_me_mppp', to: 'welcome#confirm_user_email_ip', via: [:post, :get]
    get 'max_share_reached', to: 'welcome#max_share_reached'
  end

  # for help
  get 'yelp', to: 'home_student#help'

  scope :nalos do
    get 'services', to: 'welcome#services'
    get 'actualites', to: 'welcome#actualites'
  end


  resources :local_news
  resources :teacher_classes
  resources :matieres
  scope :matiere  do
    get 'filieres_mat', to: 'matieres#filieres'
  end
  get 'admin/index'
  resources :courses
  resources :filieres
  get 'home_student/index'
  #devise_for :students
  devise_for :students, controllers: {
      sessions: 'student/sessions',
      registrations: 'student/registrations'
  }
  resources :cycle_ecoles
  # devise_for :users
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }
  resources :roles
  resources :salle_de_classes
  resources :enseignements
  resources :structures
  get 'home/index'
  #root 'home#index'

  # gestion et liste des partenaires
  scope :partners do
    get 'partners', to: "partenaire#index"
    get 'app', to: 'partenaire#app'
  end

  post 'importation', to: 'home#importation'

  scope :teacher do
    get 'apprenant', to: 'home#apprenants'
    get 'salle_classe', to: 'home#classes'
    get 'inside_classe', to: 'home#go_to_classe'
    match 'send_sms_notification_to_classe', to: 'home#send_sms_notification_to_classe', via: [:post, :get] # send notification to classeroom
    get 'apprenant_details', to: 'home#apprenant_details'
    get 'student_par_classe', to: 'home#student_par_classe'
    get 'student_par_filiere', to: 'home#student_par_filiere'
    get 'dashboard', to: 'home#dashboard'
    get 'discuss', to: 'home#discuss'

    scope :discus do
      get 'discus_chat', to: 'home#discus_chat'
      get 'discus_video', to: 'home#discus_video'
      get 'discus_schedul', to: 'home#discus_schedul'
    end

    scope :blog do
      get 'blog_index', to: 'home#blog_index'
    end

    get 'planning', to: 'home#planning'

    # gestion des elements du dashboard
    scope :dashboard do
      get 'course_dash', to: 'home#course_dash'
      get 'epreuves_dash', to: 'home#epreuve_dash'
      get 'documents_dash', to: 'home#document_dash'
    end

    #gestion des epreuves
    scope :epreuves do
      get 'epreuve', to: 'home#epreuves'
    end

    scope :messagerie do
      get 'msg', to: 'home#messagerie'
      get 'read_message', to: 'home#read_message'
      match 't_message', to: 'home#t_message', via: [:post, :get]
    end

    # gestion des live course
    scope :live_course do
      get 'live_course/index'
      get 'test_webrtc', to: 'live_course#test_webrtc'
    end

    # document sections
    scope :documents do
      get 'detail_content', to: 'documents#detail_content'
      get 'join_to_course', to: 'documents#join_to_course'
      post 'create_course_from_document', to: 'documents#create_course_from_document'
      get 'preview_course', to: 'documents#preview_course'
    end
  end
  # admin scope
  scope :admin do
    get 'index', to: 'admin#index'
    get 'read_active_document', to: 'admin#read_active_document'
    get 'index_new', to: 'admin#index_new'
    get 'stats', to: 'admin#stats_index'
    root 'admin#index', as: 'admin_route'
    get 'set_role', to: 'admin#set_role'
    get 'set_role_root', to: 'admin#set_role_root'

    # openTok stream
    get 'stream', to: 'admin#stream'


    # setup plateforme
    scope :setup do
      # liste des apprenants
      get 'setup_liste_apprenants', to: 'setup#liste_apprenants'
      get 'setup_incomplete_students', to: 'setup#liste_incomplet_apprenants'
      get 'detail_apprenant', to: 'setup#detail_apprenant'
      match 'update_apprenant', to: 'setup#update_apprenant', via: [:post, :get, :put]
      get 'manage_structure', to: "structures#manage_structure"
      get 'manage_student', to: 'students#index'
      get 'list_students', to: 'student#list'

      # gestion des ensiengnats
      get 'manage_enseignant', to: 'enseignant#index'

      # academic year
      get 'academic_year', to: 'setup#academic_year'
      get 'academic_section', to: 'setup#academic_section'
      get 'academic_salle_de_class', to: 'setup#academic_salle_de_class'

      # setup index
      get 'setup_index', to: 'setup#index'
      get 'setup_enseignant_index', to: 'setup#enseignant_index'
      get 'setup_manage_enseignant_index', to: 'setup#manage_enseignant_index'
      get 'deleted_teachers_list', to: 'setup#manage_enseignant_deleted'
      match 'setup_new_teacher', to: 'setup#new_teacher', via: [:post, :patch, :delete] # ajuoter un nouvel enseignant
      get 'setup_student_index', to: 'setup#student_idenx'
      get 'setup_notification_index', to: 'setup#notification_index'
      get 'setup_course_index', to: 'setup#course_index'
      match 'manage_matiere', to: 'setup#manage_matiere', via: [:post, :get, :delete]
      get 'setup_structure_list'  , to: 'setup#structure_list'
      get 'setup_structure_index', to: 'setup#structure_index'
      get 'setup_manage_structure_index', to: 'setup#manage_structure_index' # permet de manager un structure

      # update teacher password
      match 'update_my_t_pwd', to: 'setup#update_password', via: [:get, :post]

      # restaure teacher from deleted
      get 'restaure_teacher', to: 'setup#restaure_teacher_account'

      # manage API
      get 'setup_manage_api', to: 'setup#manage_api'
      get 'document_word_server', to: 'setup#document_word_server'
      get 'document_calc_server', to: 'setup#document_calc_server'
      get 'document_powerpoint_server', to: 'setup#document_powerpoint_server'
      # end managing API

      match 'setup_add_new_structure', to: 'setup#new_structure', via: [:post, :get, :delete] # ajout d'une nouvelle strcture
      post 'setup_update_structure', to: 'setup#update_structure' # update structure
      get 'setup_droits_index', to: 'setup#droits_index'
      get 'setup_root_structure', to: 'setup#root_structure' # gestion des utilisateurs root
      get 'setup_new_root_select', to: 'setup#new_root_select' # lister les utilisateurs qui seront les prochains root
      post 'setup_enseignant_root_role', to: 'admin#enseignant_root_role'

      # gestion des aspects liés aux matiere de la plateforme
      get 'setup_matiere_index', to: 'setup#matiere_index'
      match 'setup_new_matiere', to: 'setup#new_matiere', via: [:post, :get, :delete, :patch]
      # fin de la gestion des matiere

      # affectation
      get 'affectation_details', to: 'teacher_classes#details'
      delete 'delete_affectation', to: 'teacher_classes#delete_affectation'


      # gestion de la partie liés au notifications

      # finc de la gestion des notifications
    end

    scope :courses do
      get 'course_all', to: 'admin#course_all'
      get 'course_all_detail', to: 'admin#course_all_detail'
      get 'who_read_course', to: 'admin#who_read_course'
      get 'course_detail', to: 'admin#course_detail'
      get 'course_detail_contact_teacher', to: 'admin#course_detail_contact_teacher'
      match 'course_send_teacher_note', to: 'admin#course_send_teacher_note', via: [:get, :post]

      # CRM interface
      get 'crm', to: 'admin#crm'
      get 'calendar', to: 'admin#calendar'

      # course validation
      scope :validation do
        post 'course_validation', to: 'admin#course_validation'
        get 'course_suspension', to: 'admin#course_suspension'
        post 'course_validate_or_suspend_all', to: 'admin#course_validate_or_suspend_all'
        get 'course_delete', to: 'admin#course_delete'
      end
    end

    scope :documents do
      get 'document_all', to: 'admin#document_all'
    end

    # Managing account
    scope :account do
      get 'accounts', to: 'admin#accounts'

      # Managing matieres
      scope :matieres do
        get 'index_matieres', to: 'admin#matieres'
      end

      scope :enseignants do
        get 'index_enseignants', to: 'admin#enseignants'
        get 'teachers', to: 'admin#teachers'
      end

      scope :salle_classes do
        get 'index_salle_classes', to: 'admin#salle_classes'
      end


      # import account information
      scope :import do
        get 'import_teacher', to: 'admin#import_teacher'
        post 'import_teacher_intent', to: 'admin#import_teacher_intent'
        get 'import_student', to: 'admin#import_student'
        post 'import_student_intent', to: 'admin#import_student_intent'

        # matiere import
        post 'import_matiere_intent', to: 'admin#import_matiere_intent'
        match 'import_matiere_form', to: 'admin#import_matiere_form', via: [:get, :post]

        # enseignant import
        post 'import_enseignant_intent', to: 'admin#import_enseignant_intent'

        # salle de classe
        post 'import_salle_classe_intent', to: 'admin#import_salle_classe_intent'
      end
    end
  end

app/models/document.rb
class Document < ApplicationRecord
  has_many_attached :file
    # belongs_to :user
  has_one :course, dependent: :delete # si on détruit un document, le cours lié est egalement détruit
  belongs_to :structure

  validates :file, presence: true
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.where(user_id: current_user.id).order(created_at: :desc).page(params[:page]).per(10)
  end

  def detail_content
    data = params[:id]
    @document = Document.where(id: data, user_id: current_user.id)
  end

  def join_to_course
    current_document = params[:current_file_id]
    @current_file = Document.find(params[:document_id]).file.find(params[:current_file_id])
  end

  def preview_course
    @current_file = Document.find(params[:document_id]).file.find(params[:file_id])
  end

  def create_course_from_document
    #@course = Course.new(course_params)

    # current_course = ManageCourse.save_course(course_params)

    # send to activeJob
    puts "Data received : #{course_params}"
    CourseSaveJob.set(wait: 2.seconds).perform_later(classes_ids: params[:classes_ids], data: course_params, user_id: current_user.id, structure_id: current_user.structure_id)

    redirect_to courses_path, notice: "Vos leçons sont en cours de traitement, merci de patienter, le système vous notifiera de sa disponibilité..."

  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.fetch(:document, {}).permit(:user_id, :structure_id, file: [])
    end

  def course_params
    params.permit(:user_id, :document_id, :file_id, :matiere_id, :chapter, :classes_ids, :categorie, :tag, :extrait, :course_status_id, :structure_id)
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/detail_content.html.erb
<% @document.each do |fichier| %>
  <%= fichier.file.id %>
<% end %>

app/views/documents/index.html.erb
<% if notice.present? %>
  <div class="-m-2 text-center mb-8" id="notice">

    <div class="p-2">
      <div class="inline-flex items-center bg-white leading-none text-purple-600 rounded-full p-2 shadow text-sm">
        <span class="inline-flex bg-purple-600 text-white rounded-full h-6 px-3 justify-center items-center text-">Terminé!</span>
        <span class="inline-flex px-2">
          <%= notice %>
        </span>
      </div>
    </div>

  </div>
<% end %>

<!-- This example requires Tailwind CSS v2.0+ -->
<div class="container mx-auto px-4 sm:px-6 lg:px-8">
  <!-- Content goes here -->
  <!-- This example requires Tailwind CSS v2.0+ -->
  <div class="pb-5 border-b border-gray-200 sm:flex sm:items-center sm:justify-between">
    <h3 class="text-lg leading-6 font-medium text-gray-900">
      Liste des documents/fichiers importés
    </h3>
    <div class="mt-3 sm:mt-0 sm:ml-4">
      <%= link_to "Ajouter un/des nouveau(x)", new_document_path, class: "inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
    </div>
  </div>

  <% if @documents.empty? %>

    <div class="fixed bottom-0 inset-x-0 px-4 pb-4 sm:inset-0 sm:flex sm:items-center sm:justify-center">
      <!--
        Background overlay, show/hide based on modal state.

        Entering: "ease-out duration-300"
          From: "opacity-0"
          To: "opacity-100"
        Leaving: "ease-in duration-200"
          From: "opacity-100"
          To: "opacity-0"
      -->
      <div class="fixed inset-0 transition-opacity">
        <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
      </div>

      <!--
        Modal panel, show/hide based on modal state.

        Entering: "ease-out duration-300"
          From: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
          To: "opacity-100 translate-y-0 sm:scale-100"
        Leaving: "ease-in duration-200"
          From: "opacity-100 translate-y-0 sm:scale-100"
          To: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
      -->
      <div class="bg-white rounded-lg overflow-hidden shadow-xl transform transition-all sm:max-w-lg sm:w-full" role="dialog" aria-modal="true" aria-labelledby="modal-headline">
        <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
          <div class="sm:flex sm:items-start">
            <div class="mx-auto flex-shrink-0 flex items-center justify-center h-12 w-12 rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10">
              <svg class="h-6 w-6 text-red-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
              </svg>
            </div>
            <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
              <h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-headline">
                Aucun document/support de cours!
              </h3>
              <div class="mt-2">
                <p class="text-sm leading-5 text-gray-500">
                  Nous ne sommes pas en mesure de trouver des documents ou supports de cours précedement importé. Cele signifie surement
                  que c'est votre premiere fois d'importer des documents!.
                  Pour commencer
                </p>
              </div>
            </div>
          </div>
        </div>
        <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
      <span class="flex w-full rounded-md shadow-sm sm:ml-3 sm:w-auto">
        <%= link_to "Démarrer l'importation", new_document_path, class: "inline-flex justify-center w-full rounded-md border border-transparent px-4 py-2 bg-red-600 text-base leading-6 font-medium text-white shadow-sm hover:bg-red-500 focus:outline-none focus:border-red-700 focus:shadow-outline-red transition ease-in-out duration-150 sm:text-sm sm:leading-5" %>
      </span>
          <span class="mt-3 flex w-full rounded-md shadow-sm sm:mt-0 sm:w-auto">
          <%= link_to 'Annuler', home_index_path, class: "inline-flex justify-center w-full rounded-md border border-gray-300 px-4 py-2 bg-white text-base leading-6 font-medium text-gray-700 shadow-sm hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue transition ease-in-out duration-150 sm:text-sm sm:leading-5" %>
      </span>
        </div>
      </div>
    </div>


    </div>

  <% else %>

    <%= paginate @documents %>
    <br>

    <div class="flex flex-col">
      <div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
        <div class="align-middle inline-block min-w-full shadow overflow-hidden sm:rounded-lg border-b border-gray-200">
          <table class="min-w-full">
            <thead>
            <tr>
              <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                Date importation
              </th>
              <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                Propriétaire
              </th>
              <th class="px-6 py-3 border-b border-gray-200 bg-gray-50" colspan="3"></th>
            </tr>
            </thead>
            <tbody class="bg-white">
            <% @documents.each do |document| %>
              <tr>
                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                  <div class="flex items-center">
                    <div class="flex-shrink-0 h-10 w-10">
                      <%= image_tag 'course.png', class: "h-10 w-10" %>
                    </div>
                    <div class="ml-4">
                      <div class="text-sm leading-5 font-medium text-gray-900"><%= document.created_at.strftime("%d %b %Y, %Hh:%m") %></div>
                      <div class="text-sm leading-5 text-gray-500"><%= document.file.count %> Fichier(s)</div>
                    </div>
                  </div>
                </td>
                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                  <div class="text-sm leading-5 text-gray-900">Importé par</div>
                  <div class="text-sm leading-5 text-gray-500"><%= User.find(document.user_id).complete_name %></div>
                </td>
                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
              <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                Active
              </span>
                </td>
                <td class="px-6 py-4 whitespace-no-wrap text-right border-b border-gray-200 text-sm leading-5 font-medium"><%= link_to 'Lister les fichiers', document, class: "hover:bg-transparent text-indigo-600 hover:text-indigo-900 focus:outline-none focus:underline" %></td>
                <td class="px-6 py-4 whitespace-no-wrap text-right border-b border-gray-200 text-sm leading-5 font-medium"><%= link_to 'Editer', edit_document_path(document), class: "hover:bg-transparent text-indigo-600 hover:text-indigo-900 focus:outline-none focus:underline" %></td>
                <td class="px-6 py-4 whitespace-no-wrap text-right border-b border-gray-200 text-sm leading-5 font-medium"><%= link_to 'Supprimer', document, method: :delete, data: {confirm: 'Are you sure?'}, class: "hover:bg-transparent text-indigo-600 hover:text-indigo-900 focus:outline-none focus:underline" %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

  <% end %>

</div>

app/views/documents/new.html.erb
<div class="bg-gray-50">
  <div class="max-w-screen-xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8 lg:flex lg:items-center lg:justify-between">
    <h2 class="text-3xl leading-9 font-extrabold tracking-tight text-gray-900 sm:text-4xl sm:leading-10">
      Importer
      <br />
      <span class="text-indigo-600">un nouveau document.</span>
    </h2>
  </div>
</div>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path %>

app/views/documents/preview_course.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<div class="container mx-auto px-4 sm:px-6 lg:px-8 mt-8 mb-8">
  <!-- Content goes here -->
  <div class="pb-5 border-b border-gray-200 sm:flex sm:items-center sm:justify-between mb-8">
    <h3 class="text-lg leading-6 font-medium text-gray-900">
      Aperçu d'un document/fichier
    </h3>
    <div class="mt-3 sm:mt-0 sm:ml-4">
      <%= link_to 'Joindre ce document à un cours', join_to_course_path(document_id: params[:document_id], current_file_id: params[:file_id]), class: 'inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' %>
    </div>
  </div>

  <%= render 'layouts/previewer', data: @current_file %>

  <script>
      // import Plyr from 'plyr'

      //const player = new Plyr('#player');
      const players = Plyr.setup('.shadow');
  </script>

</div>

app/views/documents/show.html.erb
<% if notice.present? %>
  <div class="-m-2 text-center mb-8" id="notice">

    <div class="p-2">
      <div class="inline-flex items-center bg-white leading-none text-purple-600 rounded-full p-2 shadow text-sm">
        <span class="inline-flex bg-purple-600 text-white rounded-full h-6 px-3 justify-center items-center text-">Terminé!</span>
        <span class="inline-flex px-2">
            <%= notice %>
          </span>
      </div>
    </div>

  </div>
<% end %>

<!-- This example requires Tailwind CSS v2.0+ -->
<div class="container mx-auto px-4 sm:px-6 lg:px-8">
  <!-- Content goes here -->
  <!-- This example requires Tailwind CSS v2.0+ -->
  <div class="mt-4 pb-5 border-b border-gray-200">
    <h3 class="text-lg leading-6 font-medium text-gray-900">
      Détails dossier de <%= User.find(@document.user_id).complete_name %>
    </h3>
    <p class="mt-2 max-w-4xl text-sm text-gray-500">Ce dossier contient les fichiers importés par
      l'enseignant <%= User.find(@document.user_id).complete_name %>
      en date du <%= @document.created_at %>. Toutes modification de ce contenu même en tant qu'admistrateur lui sera
      notifié.</p>
  </div>

  <!-- This example requires Tailwind CSS v2.0+ -->
  <div class="mt-8">
    <h2 class="text-gray-500 text-xs font-medium uppercase tracking-wide">Pinned Projects</h2>
    <ul class="mt-3 grid grid-cols-1 gap-5 sm:gap-6 sm:grid-cols-2 lg:grid-cols-4">
      <% @document.file.each do |document| %>

        <li class="col-span-1 flex shadow-sm rounded-md">
          <div class="flex-shrink-0 flex items-center justify-center w-16 bg-purple-600 text-white text-sm font-medium rounded-l-md">
            CD
          </div>
          <div class="flex-1 flex items-center justify-between border-t border-r border-b border-gray-200 bg-white rounded-r-md truncate">
            <div class="flex-1 px-4 py-2 text-sm truncate">
              <a href="#" class="text-gray-900 font-medium hover:text-gray-600"><%= link_to excerpt(document.filename.to_s, '', radius: 30), preview_course_path(document_id: params[:id], file_id: document) %></a>
              <p class="text-gray-500"><%= document.created_at.strftime("%d %b %Y, %Hh:%m") %></p>
              <p class="text-green-500"><%= document.content_type %></p>
            </div>
            <div class="flex-shrink-0 pr-2">
              <button class="w-8 h-8 bg-white inline-flex items-center justify-center text-gray-400 rounded-full bg-transparent hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                <span class="sr-only">Open options</span>
                <!-- Heroicon name: dots-vertical -->
                <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z"/>
                </svg>
              </button>
            </div>
          </div>
        </li>

      <% end %>
    </ul>
  </div>

</div>

<% if current_user.role.name == 'teacher' %>

  <div class="bg-gray-50">
    <div class="max-w-screen-xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8 lg:flex lg:items-center lg:justify-between">
      <div class="mt-8 flex lg:flex-shrink-0 lg:mt-0">
        <div class="inline-flex rounded-md shadow">
          <%= link_to edit_document_path(@document), class: "inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" do %>
            Editer ce dossier et son contenu
            <!-- Heroicon name: mail -->
            <svg class="ml-3 -mr-1 h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path>
            </svg>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<% end %>