config/routes.rb
Rails.application.routes.draw do

  resources :rooms
  resources :structure_types
  resources :e_responses
  resources :time_tables
  get 'su/index'
  resources :jfn_support_courses
  get 'jfn/index'
  get 'jfn/admin_index'
  get 'enseignant/index'
  get 'enseignant/import'
  get 'enseignant/list'
  get 'enseignant/affectation'
  get 'enseignant/statistic'
  get 'student/index'
  get 'student/import'
  get 'demo/index'
  get 'demo/form'
  get 'demo/fuse'
  resources :trs
  resources :yrs
  resources :sequences
  resources :trimestres
  resources :annee_scolaires
  mount Notifications::Engine => '/notifications'
  #get 'share/title:string'
  devise_for :tuteurs
  resources :blogs
  resources :epreuves
  resources :messages
  resources :problemes
  #get 'people/search'

  # import data
  post 'import_gsbnal_data', to: 'salle_de_classes#import_gsbnal_data'


  resources :documents
  resources :comments
  resources :classe_matieres
  root 'welcome#index'

  scope :shares do
    get 'share', to: 'welcome#shares'
    get 'file_share_detail', to: 'welcome#file'
    match 'check_me_mppp', to: 'welcome#confirm_user_email_ip', via: [:post, :get]
    get 'max_share_reached', to: 'welcome#max_share_reached'
  end

  # for help
  get 'yelp', to: 'home_student#help'

  scope :nalos do
    get 'services', to: 'welcome#services'
    get 'actualites', to: 'welcome#actualites'
  end


  resources :local_news
  resources :teacher_classes
  resources :matieres
  scope :matiere  do
    get 'filieres_mat', to: 'matieres#filieres'
  end
  get 'admin/index'
  resources :courses
  resources :filieres
  get 'home_student/index'
  #devise_for :students
  devise_for :students, controllers: {
      sessions: 'student/sessions',
      registrations: 'student/registrations'
  }
  resources :cycle_ecoles
  # devise_for :users
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }
  resources :roles
  resources :salle_de_classes
  resources :enseignements
  resources :structures
  get 'home/index'
  #root 'home#index'

  # gestion et liste des partenaires
  scope :partners do
    get 'partners', to: "partenaire#index"
    get 'app', to: 'partenaire#app'
  end

  post 'importation', to: 'home#importation'

  scope :teacher do
    get 'apprenant', to: 'home#apprenants'
    get 'salle_classe', to: 'home#classes'
    get 'inside_classe', to: 'home#go_to_classe'
    match 'send_sms_notification_to_classe', to: 'home#send_sms_notification_to_classe', via: [:post, :get] # send notification to classeroom
    get 'apprenant_details', to: 'home#apprenant_details'
    get 'student_par_classe', to: 'home#student_par_classe'
    get 'student_par_filiere', to: 'home#student_par_filiere'
    get 'dashboard', to: 'home#dashboard'
    get 'discuss', to: 'home#discuss'

    scope :discus do
      get 'discus_chat', to: 'home#discus_chat'
      get 'discus_video', to: 'home#discus_video'
      get 'discus_schedul', to: 'home#discus_schedul'
    end

    scope :blog do
      get 'blog_index', to: 'home#blog_index'
    end

    get 'planning', to: 'home#planning'

    # gestion des elements du dashboard
    scope :dashboard do
      get 'course_dash', to: 'home#course_dash'
      get 'epreuves_dash', to: 'home#epreuve_dash'
      get 'documents_dash', to: 'home#document_dash'
    end

    #gestion des epreuves
    scope :epreuves do
      get 'epreuve', to: 'home#epreuves'
    end

    scope :messagerie do
      get 'msg', to: 'home#messagerie'
      get 'read_message', to: 'home#read_message'
      match 't_message', to: 'home#t_message', via: [:post, :get]
    end

    # gestion des live course
    scope :live_course do
      get 'live_course/index'
      get 'test_webrtc', to: 'live_course#test_webrtc'
    end

    # document sections
    scope :documents do
      get 'detail_content', to: 'documents#detail_content'
      get 'join_to_course', to: 'documents#join_to_course'
      post 'create_course_from_document', to: 'documents#create_course_from_document'
      get 'preview_course', to: 'documents#preview_course'
    end
  end
  # admin scope
  scope :admin do
    get 'index', to: 'admin#index'
    get 'read_active_document', to: 'admin#read_active_document'
    get 'index_new', to: 'admin#index_new'
    get 'stats', to: 'admin#stats_index'
    root 'admin#index', as: 'admin_route'
    get 'set_role', to: 'admin#set_role'
    get 'set_role_root', to: 'admin#set_role_root'

    # openTok stream
    get 'stream', to: 'admin#stream'


    # setup plateforme
    scope :setup do
      # liste des apprenants
      get 'setup_liste_apprenants', to: 'setup#liste_apprenants'
      get 'setup_incomplete_students', to: 'setup#liste_incomplet_apprenants'
      get 'detail_apprenant', to: 'setup#detail_apprenant'
      match 'update_apprenant', to: 'setup#update_apprenant', via: [:post, :get, :put]
      get 'manage_structure', to: "structures#manage_structure"
      get 'manage_student', to: 'students#index'
      get 'list_students', to: 'student#list'

      # gestion des ensiengnats
      get 'manage_enseignant', to: 'enseignant#index'

      # academic year
      get 'academic_year', to: 'setup#academic_year'
      get 'academic_section', to: 'setup#academic_section'
      get 'academic_salle_de_class', to: 'setup#academic_salle_de_class'

      # setup index
      get 'setup_index', to: 'setup#index'
      get 'setup_enseignant_index', to: 'setup#enseignant_index'
      get 'setup_manage_enseignant_index', to: 'setup#manage_enseignant_index'
      get 'deleted_teachers_list', to: 'setup#manage_enseignant_deleted'
      match 'setup_new_teacher', to: 'setup#new_teacher', via: [:post, :patch, :delete] # ajuoter un nouvel enseignant
      get 'setup_student_index', to: 'setup#student_idenx'
      get 'setup_notification_index', to: 'setup#notification_index'
      get 'setup_course_index', to: 'setup#course_index'
      match 'manage_matiere', to: 'setup#manage_matiere', via: [:post, :get, :delete]
      get 'setup_structure_list'  , to: 'setup#structure_list'
      get 'setup_structure_index', to: 'setup#structure_index'
      get 'setup_manage_structure_index', to: 'setup#manage_structure_index' # permet de manager un structure

      # update teacher password
      match 'update_my_t_pwd', to: 'setup#update_password', via: [:get, :post]

      # restaure teacher from deleted
      get 'restaure_teacher', to: 'setup#restaure_teacher_account'

      # manage API
      get 'setup_manage_api', to: 'setup#manage_api'
      get 'document_word_server', to: 'setup#document_word_server'
      get 'document_calc_server', to: 'setup#document_calc_server'
      get 'document_powerpoint_server', to: 'setup#document_powerpoint_server'
      # end managing API

      match 'setup_add_new_structure', to: 'setup#new_structure', via: [:post, :get, :delete] # ajout d'une nouvelle strcture
      post 'setup_update_structure', to: 'setup#update_structure' # update structure
      get 'setup_droits_index', to: 'setup#droits_index'
      get 'setup_root_structure', to: 'setup#root_structure' # gestion des utilisateurs root
      get 'setup_new_root_select', to: 'setup#new_root_select' # lister les utilisateurs qui seront les prochains root
      post 'setup_enseignant_root_role', to: 'admin#enseignant_root_role'

      # gestion des aspects liés aux matiere de la plateforme
      get 'setup_matiere_index', to: 'setup#matiere_index'
      match 'setup_new_matiere', to: 'setup#new_matiere', via: [:post, :get, :delete, :patch]
      # fin de la gestion des matiere

      # affectation
      get 'affectation_details', to: 'teacher_classes#details'
      delete 'delete_affectation', to: 'teacher_classes#delete_affectation'


      # gestion de la partie liés au notifications

      # finc de la gestion des notifications
    end

    scope :courses do
      get 'course_all', to: 'admin#course_all'
      get 'course_all_detail', to: 'admin#course_all_detail'
      get 'who_read_course', to: 'admin#who_read_course'
      get 'course_detail', to: 'admin#course_detail'
      get 'course_detail_contact_teacher', to: 'admin#course_detail_contact_teacher'
      match 'course_send_teacher_note', to: 'admin#course_send_teacher_note', via: [:get, :post]

      # CRM interface
      get 'crm', to: 'admin#crm'
      get 'calendar', to: 'admin#calendar'

      # course validation
      scope :validation do
        post 'course_validation', to: 'admin#course_validation'
        get 'course_suspension', to: 'admin#course_suspension'
        post 'course_validate_or_suspend_all', to: 'admin#course_validate_or_suspend_all'
        get 'course_delete', to: 'admin#course_delete'
      end
    end

    scope :documents do
      get 'document_all', to: 'admin#document_all'
    end

    # Managing account
    scope :account do
      get 'accounts', to: 'admin#accounts'

      # Managing matieres
      scope :matieres do
        get 'index_matieres', to: 'admin#matieres'
      end

      scope :enseignants do
        get 'index_enseignants', to: 'admin#enseignants'
        get 'teachers', to: 'admin#teachers'
      end

      scope :salle_classes do
        get 'index_salle_classes', to: 'admin#salle_classes'
      end


      # import account information
      scope :import do
        get 'import_teacher', to: 'admin#import_teacher'
        post 'import_teacher_intent', to: 'admin#import_teacher_intent'
        get 'import_student', to: 'admin#import_student'
        post 'import_student_intent', to: 'admin#import_student_intent'

        # matiere import
        post 'import_matiere_intent', to: 'admin#import_matiere_intent'
        match 'import_matiere_form', to: 'admin#import_matiere_form', via: [:get, :post]

        # enseignant import
        post 'import_enseignant_intent', to: 'admin#import_enseignant_intent'

        # salle de classe
        post 'import_salle_classe_intent', to: 'admin#import_salle_classe_intent'
      end
    end
  end

app/models/probleme.rb
class Probleme < ApplicationRecord
  belongs_to :student

  has_rich_text :content
end

app/controllers/problemes_controller.rb
class ProblemesController < ApplicationController
  before_action :set_probleme, only: [:show, :edit, :update, :destroy]

  # GET /problemes
  # GET /problemes.json
  def index
    @problemes = Probleme.where(student_id: current_student.id)
  end

  # GET /problemes/1
  # GET /problemes/1.json
  def show
  end

  # GET /problemes/new
  def new
    @probleme = Probleme.new
  end

  # GET /problemes/1/edit
  def edit
  end

  # POST /problemes
  # POST /problemes.json
  def create
    @probleme = Probleme.new(probleme_params)

    respond_to do |format|
      if @probleme.save
        format.html { redirect_to @probleme, notice: 'Probleme was successfully created.' }
        format.json { render :show, status: :created, location: @probleme }
      else
        format.html { render :new }
        format.json { render json: @probleme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /problemes/1
  # PATCH/PUT /problemes/1.json
  def update
    respond_to do |format|
      if @probleme.update(probleme_params)
        format.html { redirect_to @probleme, notice: 'Probleme was successfully updated.' }
        format.json { render :show, status: :ok, location: @probleme }
      else
        format.html { render :edit }
        format.json { render json: @probleme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problemes/1
  # DELETE /problemes/1.json
  def destroy
    @probleme.destroy
    respond_to do |format|
      format.html { redirect_to problemes_url, notice: 'Probleme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_probleme
      @probleme = Probleme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def probleme_params
      params.require(:probleme).permit(:title, :student_id)
    end
end

app/helpers/problemes_helper.rb
module ProblemesHelper
end

app/views/problemes/_form.html.erb
<%= form_with(model: probleme, local: true) do |form| %>
  <% if probleme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(probleme.errors.count, "error") %> prohibited this probleme from being saved:</h2>

      <ul>
        <% probleme.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<% if student_signed_in? %>
  <%= form.hidden_field :student_id, value: current_student.id %>
<% elsif user_signed_in? %>
    <%= form.hidden_field :student_id, value: current_user.id %>
<% end %>

  <div class="field">
    <%= form.label 'Libellé du problème', class: 'text-md mb-4 mt-8 font-semibold' %>
    <%= form.text_field :title, class: 'appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500' %>
  </div>

  <div class="field">
    <%= form.label "Description de votre problème", class: 'text-md mb-4 mt-8 font-semibold' %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit 'Soumettre ce problème', class: 'bg-blue-500 hover:bg-blue-400 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 rounded' %>
  </div>
<% end %>

app/views/problemes/edit.html.erb
<h1>Editing Probleme</h1>

<%= render 'form', probleme: @probleme %>

<%= link_to 'Show', @probleme %> |
<%= link_to 'Back', problemes_path %>

app/views/problemes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Liste des problèmes</h1>

<div class="flex flex-col">
  <div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
    <div class="align-middle inline-block min-w-full shadow overflow-hidden sm:rounded-lg border-b border-gray-200">
      <table class="min-w-full">
        <thead>
        <tr>
          <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
            Date soumission
          </th>
          <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
            Libellé problème
          </th>
          <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
            Status
          </th>
          <th class="px-6 py-3 border-b border-gray-200 bg-gray-50" colspan="3"></th>
        </tr>
        </thead>
        <tbody class="bg-white">
        <% @problemes.each do |probleme| %>
          <tr>
            <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
              <div class="flex items-center">
                <div class="flex-shrink-0 h-10 w-10">
                  <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt=""/>
                </div>
                <div class="ml-4">
                  <div class="text-sm leading-5 font-medium text-gray-900"><%= probleme.created_at.strftime("%d %b %Y") %></div>
                  <div class="text-sm leading-5 text-gray-500">Par <%= probleme.student.complete_name %></div>
                </div>
              </div>
            </td>
            <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
              <div class="text-sm leading-5 text-gray-900"><%= probleme.title %></div>
              <div class="text-sm leading-5 text-gray-500">Human Resources</div>
            </td>
            <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                  Non consulté
                </span>
            </td>
            <td class="px-6 py-4 whitespace-no-wrap text-right border-b border-gray-200 text-sm leading-5 font-medium"><%= link_to 'Show', probleme %></td>
            <td class="px-6 py-4 whitespace-no-wrap text-right border-b border-gray-200 text-sm leading-5 font-medium"><%= link_to 'Edit', edit_probleme_path(probleme) %></td>
            <td class="px-6 py-4 whitespace-no-wrap text-right border-b border-gray-200 text-sm leading-5 font-medium"><%= link_to 'Destroy', probleme, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<br>

<%= link_to 'Nouveau problème', new_probleme_path, class: 'bg-blue-500 hover:bg-blue-400 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 rounded' %>

app/views/problemes/new.html.erb
<h1 class="text-xl font-semibold text-gray-500">Soumettre un problème</h1>

<%= render 'form', probleme: @probleme %>

<%#= link_to 'Back', problemes_path %>

app/views/problemes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @probleme.title %>
</p>

<%= link_to 'Edit', edit_probleme_path(@probleme) %> |
<%= link_to 'Back', problemes_path %>