config/routes.rb
Rails.application.routes.draw do

  resources :rooms
  resources :structure_types
  resources :e_responses
  resources :time_tables
  get 'su/index'
  resources :jfn_support_courses
  get 'jfn/index'
  get 'jfn/admin_index'
  get 'enseignant/index'
  get 'enseignant/import'
  get 'enseignant/list'
  get 'enseignant/affectation'
  get 'enseignant/statistic'
  get 'student/index'
  get 'student/import'
  get 'demo/index'
  get 'demo/form'
  get 'demo/fuse'
  resources :trs
  resources :yrs
  resources :sequences
  resources :trimestres
  resources :annee_scolaires
  mount Notifications::Engine => '/notifications'
  #get 'share/title:string'
  devise_for :tuteurs
  resources :blogs
  resources :epreuves
  resources :messages
  resources :problemes
  #get 'people/search'

  # import data
  post 'import_gsbnal_data', to: 'salle_de_classes#import_gsbnal_data'


  resources :documents
  resources :comments
  resources :classe_matieres
  root 'welcome#index'

  scope :shares do
    get 'share', to: 'welcome#shares'
    get 'file_share_detail', to: 'welcome#file'
    match 'check_me_mppp', to: 'welcome#confirm_user_email_ip', via: [:post, :get]
    get 'max_share_reached', to: 'welcome#max_share_reached'
  end

  # for help
  get 'yelp', to: 'home_student#help'

  scope :nalos do
    get 'services', to: 'welcome#services'
    get 'actualites', to: 'welcome#actualites'
  end


  resources :local_news
  resources :teacher_classes
  resources :matieres
  scope :matiere  do
    get 'filieres_mat', to: 'matieres#filieres'
  end
  get 'admin/index'
  resources :courses
  resources :filieres
  get 'home_student/index'
  #devise_for :students
  devise_for :students, controllers: {
      sessions: 'student/sessions',
      registrations: 'student/registrations'
  }
  resources :cycle_ecoles
  # devise_for :users
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }
  resources :roles
  resources :salle_de_classes
  resources :enseignements
  resources :structures
  get 'home/index'
  #root 'home#index'

  # gestion et liste des partenaires
  scope :partners do
    get 'partners', to: "partenaire#index"
    get 'app', to: 'partenaire#app'
  end

  post 'importation', to: 'home#importation'

  scope :teacher do
    get 'apprenant', to: 'home#apprenants'
    get 'salle_classe', to: 'home#classes'
    get 'inside_classe', to: 'home#go_to_classe'
    match 'send_sms_notification_to_classe', to: 'home#send_sms_notification_to_classe', via: [:post, :get] # send notification to classeroom
    get 'apprenant_details', to: 'home#apprenant_details'
    get 'student_par_classe', to: 'home#student_par_classe'
    get 'student_par_filiere', to: 'home#student_par_filiere'
    get 'dashboard', to: 'home#dashboard'
    get 'discuss', to: 'home#discuss'

    scope :discus do
      get 'discus_chat', to: 'home#discus_chat'
      get 'discus_video', to: 'home#discus_video'
      get 'discus_schedul', to: 'home#discus_schedul'
    end

    scope :blog do
      get 'blog_index', to: 'home#blog_index'
    end

    get 'planning', to: 'home#planning'

    # gestion des elements du dashboard
    scope :dashboard do
      get 'course_dash', to: 'home#course_dash'
      get 'epreuves_dash', to: 'home#epreuve_dash'
      get 'documents_dash', to: 'home#document_dash'
    end

    #gestion des epreuves
    scope :epreuves do
      get 'epreuve', to: 'home#epreuves'
    end

    scope :messagerie do
      get 'msg', to: 'home#messagerie'
      get 'read_message', to: 'home#read_message'
      match 't_message', to: 'home#t_message', via: [:post, :get]
    end

    # gestion des live course
    scope :live_course do
      get 'live_course/index'
      get 'test_webrtc', to: 'live_course#test_webrtc'
    end

    # document sections
    scope :documents do
      get 'detail_content', to: 'documents#detail_content'
      get 'join_to_course', to: 'documents#join_to_course'
      post 'create_course_from_document', to: 'documents#create_course_from_document'
      get 'preview_course', to: 'documents#preview_course'
    end
  end
  # admin scope
  scope :admin do
    get 'index', to: 'admin#index'
    get 'read_active_document', to: 'admin#read_active_document'
    get 'index_new', to: 'admin#index_new'
    get 'stats', to: 'admin#stats_index'
    root 'admin#index', as: 'admin_route'
    get 'set_role', to: 'admin#set_role'
    get 'set_role_root', to: 'admin#set_role_root'

    # openTok stream
    get 'stream', to: 'admin#stream'


    # setup plateforme
    scope :setup do
      # liste des apprenants
      get 'setup_liste_apprenants', to: 'setup#liste_apprenants'
      get 'setup_incomplete_students', to: 'setup#liste_incomplet_apprenants'
      get 'detail_apprenant', to: 'setup#detail_apprenant'
      match 'update_apprenant', to: 'setup#update_apprenant', via: [:post, :get, :put]
      get 'manage_structure', to: "structures#manage_structure"
      get 'manage_student', to: 'students#index'
      get 'list_students', to: 'student#list'

      # gestion des ensiengnats
      get 'manage_enseignant', to: 'enseignant#index'

      # academic year
      get 'academic_year', to: 'setup#academic_year'
      get 'academic_section', to: 'setup#academic_section'
      get 'academic_salle_de_class', to: 'setup#academic_salle_de_class'

      # setup index
      get 'setup_index', to: 'setup#index'
      get 'setup_enseignant_index', to: 'setup#enseignant_index'
      get 'setup_manage_enseignant_index', to: 'setup#manage_enseignant_index'
      get 'deleted_teachers_list', to: 'setup#manage_enseignant_deleted'
      match 'setup_new_teacher', to: 'setup#new_teacher', via: [:post, :patch, :delete] # ajuoter un nouvel enseignant
      get 'setup_student_index', to: 'setup#student_idenx'
      get 'setup_notification_index', to: 'setup#notification_index'
      get 'setup_course_index', to: 'setup#course_index'
      match 'manage_matiere', to: 'setup#manage_matiere', via: [:post, :get, :delete]
      get 'setup_structure_list'  , to: 'setup#structure_list'
      get 'setup_structure_index', to: 'setup#structure_index'
      get 'setup_manage_structure_index', to: 'setup#manage_structure_index' # permet de manager un structure

      # update teacher password
      match 'update_my_t_pwd', to: 'setup#update_password', via: [:get, :post]

      # restaure teacher from deleted
      get 'restaure_teacher', to: 'setup#restaure_teacher_account'

      # manage API
      get 'setup_manage_api', to: 'setup#manage_api'
      get 'document_word_server', to: 'setup#document_word_server'
      get 'document_calc_server', to: 'setup#document_calc_server'
      get 'document_powerpoint_server', to: 'setup#document_powerpoint_server'
      # end managing API

      match 'setup_add_new_structure', to: 'setup#new_structure', via: [:post, :get, :delete] # ajout d'une nouvelle strcture
      post 'setup_update_structure', to: 'setup#update_structure' # update structure
      get 'setup_droits_index', to: 'setup#droits_index'
      get 'setup_root_structure', to: 'setup#root_structure' # gestion des utilisateurs root
      get 'setup_new_root_select', to: 'setup#new_root_select' # lister les utilisateurs qui seront les prochains root
      post 'setup_enseignant_root_role', to: 'admin#enseignant_root_role'

      # gestion des aspects liés aux matiere de la plateforme
      get 'setup_matiere_index', to: 'setup#matiere_index'
      match 'setup_new_matiere', to: 'setup#new_matiere', via: [:post, :get, :delete, :patch]
      # fin de la gestion des matiere

      # affectation
      get 'affectation_details', to: 'teacher_classes#details'
      delete 'delete_affectation', to: 'teacher_classes#delete_affectation'


      # gestion de la partie liés au notifications

      # finc de la gestion des notifications
    end

    scope :courses do
      get 'course_all', to: 'admin#course_all'
      get 'course_all_detail', to: 'admin#course_all_detail'
      get 'who_read_course', to: 'admin#who_read_course'
      get 'course_detail', to: 'admin#course_detail'
      get 'course_detail_contact_teacher', to: 'admin#course_detail_contact_teacher'
      match 'course_send_teacher_note', to: 'admin#course_send_teacher_note', via: [:get, :post]

      # CRM interface
      get 'crm', to: 'admin#crm'
      get 'calendar', to: 'admin#calendar'

      # course validation
      scope :validation do
        post 'course_validation', to: 'admin#course_validation'
        get 'course_suspension', to: 'admin#course_suspension'
        post 'course_validate_or_suspend_all', to: 'admin#course_validate_or_suspend_all'
        get 'course_delete', to: 'admin#course_delete'
      end
    end

    scope :documents do
      get 'document_all', to: 'admin#document_all'
    end

    # Managing account
    scope :account do
      get 'accounts', to: 'admin#accounts'

      # Managing matieres
      scope :matieres do
        get 'index_matieres', to: 'admin#matieres'
      end

      scope :enseignants do
        get 'index_enseignants', to: 'admin#enseignants'
        get 'teachers', to: 'admin#teachers'
      end

      scope :salle_classes do
        get 'index_salle_classes', to: 'admin#salle_classes'
      end


      # import account information
      scope :import do
        get 'import_teacher', to: 'admin#import_teacher'
        post 'import_teacher_intent', to: 'admin#import_teacher_intent'
        get 'import_student', to: 'admin#import_student'
        post 'import_student_intent', to: 'admin#import_student_intent'

        # matiere import
        post 'import_matiere_intent', to: 'admin#import_matiere_intent'
        match 'import_matiere_form', to: 'admin#import_matiere_form', via: [:get, :post]

        # enseignant import
        post 'import_enseignant_intent', to: 'admin#import_enseignant_intent'

        # salle de classe
        post 'import_salle_classe_intent', to: 'admin#import_salle_classe_intent'
      end
    end
  end

app/models/matiere.rb
class Matiere < ApplicationRecord
  has_many :courses, dependent: :delete_all
  # has_many :teacher_classes
  belongs_to :structure
  belongs_to :filiere
  belongs_to :user

  before_create :set_token, if: :new_record?

  validates :name, presence: {message: "%{value} à deja été utilisé."}

  # for epreuves
  # has_many :epreuves

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Matiere.create!(row.to_hash)
    end
  end

  def matiere_with_initial
    name.to_s
  end

  private
  def set_token
    self.token = SecureRandom.hex(12)
  end
end

app/controllers/matieres_controller.rb
class MatieresController < ApplicationController
  before_action :set_matiere, only: [:show, :edit, :update, :destroy]

  # GET /matieres
  # GET /matieres.json
  def index
    if current_user.role.name == "root"
      @matieres = Matiere.all.page(params[:page]).per(20)
    else
      current_structure = current_user.structure #Structure.find_by_token(params[:token])
      @matieres = Matiere.where(structure_id: current_structure.id).page(params[:page]).per(20)
    end
  end

  # GET /matieres/1
  # GET /matieres/1.json
  def show
  end

  # GET /matieres/new
  def new
    @matiere = Matiere.new
  end

  # GET /matieres/1/edit
  def edit
  end

  # POST /matieres
  # POST /matieres.json
  def create
    @matiere = Matiere.new(matiere_params)

    respond_to do |format|
      if @matiere.save
        format.html { redirect_to @matiere, notice: 'Matiere was successfully created.' }
        format.json { render :show, status: :created, location: @matiere }
      else
        format.html { render :new }
        format.json { render json: @matiere.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matieres/1
  # PATCH/PUT /matieres/1.json
  def update
    respond_to do |format|
      if @matiere.update(matiere_params)
        format.html { redirect_to @matiere, notice: 'Matiere was successfully updated.' }
        format.json { render :show, status: :ok, location: @matiere }
      else
        format.html { render :edit }
        format.json { render json: @matiere.errors, status: :unprocessable_entity }
      end
    end
  end

  # liste matiere par filiere
  def filieres
    @filieres = Filiere.where(structure_id: current_user.structure_id)
  end

  # DELETE /matieres/1
  # DELETE /matieres/1.json
  def destroy
    @matiere.destroy
    respond_to do |format|
      format.html { redirect_to matieres_url, notice: 'Matiere was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_matiere
      @matiere = Matiere.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def matiere_params
      params.require(:matiere).permit(:name, :descriptioin, :structure_id, :user_id, :filiere_id)
    end
end

app/helpers/matieres_helper.rb
module MatieresHelper
end

app/views/matieres/edit.html.erb
<h1>Editing Matiere</h1>

<%= render 'form', matiere: @matiere %>

<%= link_to 'Show', @matiere %> |
<%= link_to 'Back', matieres_path %>

app/views/matieres/index.html.erb
<% if notice.present? %>
  <div class="-m-2 text-center mb-8" id="notice">

    <div class="p-2">
      <div class="inline-flex items-center bg-white leading-none text-purple-600 rounded-full p-2 shadow text-sm">
        <span class="inline-flex bg-purple-600 text-white rounded-full h-6 px-3 justify-center items-center text-">Terminé!</span>
        <span class="inline-flex px-2">
          <%= notice %>
        </span>
      </div>
    </div>
  </div>
<% end %>



<!-- This example requires Tailwind CSS v2.0+ -->
<div class="container mx-auto px-4 sm:px-6 lg:px-8">
  <!-- Content goes here -->

  <!--
  This example requires Tailwind CSS v2.0+

  This example requires some changes to your config:

  ```
  // tailwind.config.js
  module.exports = {
    // ...
    plugins: [
      // ...
      require('@tailwindcss/forms'),
    ]
  }
  ```
-->
  <div class="relative pb-5 border-b border-gray-200 sm:pb-0 mt-4">
    <div class="md:flex md:items-center md:justify-between">
      <h3 class="text-lg leading-6 font-medium text-gray-900">
        Matières enregistrées & disponibles
      </h3>
      <div class="mt-3 flex md:mt-0 md:absolute md:top-3 md:right-0">
        <button type="button" class="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          Share
        </button>
        <%= link_to "Nouvelle matière", new_matiere_path, class: "ml-3 inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
      </div>
    </div>
    <div class="mt-4">
      <!-- Dropdown menu on small screens -->
      <div class="sm:hidden">
        <label for="selectedTab" class="sr-only">Select a tab</label>
        <select id="selectedTab" class="block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md">
          <option>Applied</option>

          <option>Phone Screening</option>

          <option selected>Toutes les matières</option>

          <option>Matières par filière</option>

          <option>Hired</option>
        </select>
      </div>
      <!-- Tabs at small breakpoint and up -->
      <div class="hidden sm:block">
        <nav class="-mb-px flex space-x-8">
          <a href="#" class="whitespace-nowrap pb-4 px-1 border-b-2 border-transparent font-medium text-sm text-gray-500 hover:text-gray-700 hover:border-gray-300">
            Applied
          </a>

          <a href="#" class="whitespace-nowrap pb-4 px-1 border-b-2 border-transparent font-medium text-sm text-gray-500 hover:text-gray-700 hover:border-gray-300">
            Phone Screening
          </a>

          <a href="#" class="whitespace-nowrap pb-4 px-1 border-b-2 border-indigo-500 font-medium text-sm text-indigo-600" aria-current="page">
            Toutes les matières
          </a>

          <%= link_to "Matières par filière", filieres_mat_path, class: "whitespace-nowrap pb-4 px-1 border-b-2 border-transparent font-medium text-sm text-gray-500 hover:text-gray-700 hover:border-gray-300" %>

          <a href="#" class="whitespace-nowrap pb-4 px-1 border-b-2 border-transparent font-medium text-sm text-gray-500 hover:text-gray-700 hover:border-gray-300">
            Hired
          </a>
        </nav>
      </div>
    </div>
  </div>

  <% if @matieres.empty? %>

    <div class="md:flex bg-transparent rounded-lg p-6 text-center justify-center">

      <div class="md:flex bg-transparent rounded-lg p-6 text-center justify-center">

        <%= image_tag('iconfinder_video-slides-layers-player-ui_3993849.png', class: 'mr-4 opacity-50 mx-auto md:mx-0 md:mr-6 w-100 h-100', height: 100, width: 100) %>

        <div class="text-center md:text-left">
          <h2 class="text-lg mt-8">Aucune matière trouvée.</h2> <br>
          <%= link_to 'Ajouter une matiere?', new_matiere_path, class: "hover:bg-transparent hover:text-indigo-500" %>
        </div>
      </div>

    </div>

  <% else %>

    <%= paginate @matieres %>
    <br>

    <!--
    Tailwind UI components require Tailwind CSS v1.8 and the @tailwindcss/ui plugin.
    Read the documentation to get started: https://tailwindui.com/documentation
  -->
    <div class="flex flex-col">
      <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
          <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
            <table class="min-w-full divide-y divide-gray-200">
              <thead>
              <tr>
                <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                  Libellé matière
                </th>
                <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                  Filière
                </th>
                <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                  Status
                </th>
                <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                  Etablissement
                </th>
                <th class="px-6 py-3 bg-gray-50" colspan="3"></th>
              </tr>
              </thead>
              <tbody class="bg-white divide-y divide-gray-200">
              <% @matieres.each do |matiere| %>
                <tr>
                  <td class="px-6 py-4 whitespace-no-wrap">
                    <div class="flex items-center">
                      <div class="flex-shrink-0 h-10 w-10">
                        <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=facearea&amp;facepad=4&amp;w=256&amp;h=256&amp;q=60" alt="">
                      </div>
                      <div class="ml-4">
                        <div class="text-sm leading-5 font-medium text-gray-900">
                          <%= matiere.name %>
                        </div>
                        <div class="text-sm leading-5 text-gray-500">
                          <%= matiere.user_id.nil? ? "Aucun user" : matiere.user.email %>
                        </div>
                      </div>
                    </div>
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap">
                    <div class="text-sm leading-5 text-gray-900"><%= matiere.filiere_id.nil? ? "Aucune filiere" : matiere.filiere.name %></div>
                    <div class="text-sm leading-5 text-gray-500"><%= matiere.created_at %></div>
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap">
                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                  Active
                </span>
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                    <%= matiere.structure.name %>
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium">
                    <%= link_to 'Voir', matiere, class: "text-indigo-600 hover:text-indigo-900" %>
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium">
                    <%= link_to 'Editer', edit_matiere_path(matiere), class: "text-indigo-600 hover:text-indigo-900" %>
                  </td>
                  <td class="px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium">
                    <%= link_to 'Supprimer', matiere, method: :delete, data: {confirm: 'Are you sure?'}, class: "text-indigo-600 hover:text-indigo-900" %>
                  </td>
                </tr>
              <% end %>

              <!-- More rows... -->
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

  <% end %>

</div>

app/views/matieres/new.html.erb
<!--
  Tailwind UI components require Tailwind CSS v1.8 and the @tailwindcss/ui plugin.
  Read the documentation to get started: https://tailwindui.com/documentation
-->
<div class="bg-gray-50">
  <div class="max-w-screen-xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8 lg:flex lg:items-center lg:justify-between">
    <h2 class="text-3xl leading-9 font-extrabold tracking-tight text-gray-900 sm:text-4xl sm:leading-10">
      Ajouter une nouvelle
      <br>
      <span class="text-indigo-600">Matière/unité enseignement.</span>
    </h2>
<!--    <div class="mt-8 flex lg:flex-shrink-0 lg:mt-0">-->
<!--      <div class="inline-flex rounded-md shadow">-->
<!--        <a href="#" class="inline-flex items-center justify-center px-5 py-3 border border-transparent text-base leading-6 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline transition duration-150 ease-in-out">-->
<!--          Get started-->
<!--        </a>-->
<!--      </div>-->
<!--      <div class="ml-3 inline-flex rounded-md shadow">-->
<!--        <a href="#" class="inline-flex items-center justify-center px-5 py-3 border border-transparent text-base leading-6 font-medium rounded-md text-indigo-600 bg-white hover:text-indigo-500 focus:outline-none focus:shadow-outline transition duration-150 ease-in-out">-->
<!--          Learn more-->
<!--        </a>-->
<!--      </div>-->
<!--    </div>-->
  </div>
</div>


<%= render 'form', matiere: @matiere %>

<%= link_to 'Annuler', matieres_path %>

app/views/matieres/show.html.erb
<p id="notice"><%= notice %></p>
<div class="bg-gray-50">
  <div class="max-w-screen-xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8 lg:flex lg:items-center lg:justify-between">
    <h2 class="text-3xl leading-9 font-extrabold tracking-tight text-gray-900 sm:text-4xl sm:leading-10">
      Editer
      <br />
      <span class="text-indigo-600">matière</span>
    </h2>
    <div class="mt-8 flex lg:flex-shrink-0 lg:mt-0">
      <div class="inline-flex rounded-md shadow">
        <%= link_to 'Back', matieres_path, class: "inline-flex items-center justify-center px-5 py-3 border border-transparent text-base leading-6 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline transition duration-150 ease-in-out" %>
      </div>
      <div class="ml-3 inline-flex rounded-md shadow">
        <%= link_to 'Edit', edit_matiere_path(@matiere), class: "inline-flex items-center justify-center px-5 py-3 border border-transparent text-base leading-6 font-medium rounded-md text-indigo-600 bg-white hover:text-indigo-500 focus:outline-none focus:shadow-outline transition duration-150 ease-in-out" %>
      </div>
    </div>
  </div>
</div>
<p>
  <strong>Name:</strong>
  <%= @matiere.name %>
</p>

<p>
  <strong>Descriptioin:</strong>
  <%= @matiere.descriptioin %>
</p>

<%= link_to 'Edit', edit_matiere_path(@matiere) %> |
<%= link_to 'Back', matieres_path %>